### ISSUE TITLE
Tb_settings leads to "you don't have the required permissions" and mentioning level 3 permissions

### ISSUE THREAD

**Issue by asylumexp** [AzamServer/LowDurabilityAlert#1]
![image](https://user-images.githubusercontent.com/54530346/152068847-9fdb0797-c352-451f-90fe-1e4547d47c1d.png)
whenever I run tb_settings, I get that message; I'm op'd and have all permissions that the plugin page mentions, yet I still cannot run tb_settings. Know why?

**Comment by aazam476** [comment]
May I ask what "tb_settings" is?

**Comment by asylumexp** [comment]
Oops, sorry, somehow I mixed up thinking that command was from your plugin; it was from another one I installed at the same time; sorry about that!

**Comment by aazam476** [comment]
No problem :D
